version: 2
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: 
          command: yarn
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: ~/project
          paths:
            - node_modules

  ios:
    macos:
      xcode: "9.0"
    working_directory: ~/project/ios
    environment:
      FL_OUTPUT_DIR: ~/project/output
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout:
          path: ~/project
      - run:
          name: Set Ruby Version
          command:  echo "ruby-2.4" > ~/.ruby-version
      # Not using a workspace here as Node and Yarn versions
      # differ between the macOS image and the Docker containers above.
      - run: yarn
      - restore_cache:
          key: v2-bundle-{{ checksum "~/project/ios/Gemfile.lock" }}
      - run: bundle install --path ~/project/vendor/bundle
      - save_cache:
          key: v2-bundle-{{ checksum "~/project/ios/Gemfile.lock" }}
          paths: 
            - ~/project/vendor/bundle
      - restore_cache:
          key: pods-{{ checksum "Podfile" }}
      - run: bundle exec pod install
      - save_cache:
          key: pods-{{ checksum "Podfile" }}
          paths: 
            - ~/project/ios/Pods
      - run: bundle exec fastlane beta_c

workflows:
  version: 2
  node-android-ios:
    jobs:
      - build:
          filters:
            branches:
              only: master
            tags:
              ignore: /^v.*/
      - ios:
          requires:            
            - build
          filters:
            branches:
              only: master