version: 2
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: 
          command: yarn
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: ~/project
          paths:
            - node_modules

  ios:
    macos:
      xcode: "9.0"
    working_directory: ~/project/ios
    environment:
      FL_OUTPUT_DIR: ~/project/output
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout
      - run:
        name: Fetch CocoaPods Specs
        command: |
          curl https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash -s cf
      - run:
        name: Install CocoaPods
        command: pod install --verbose
      - run:
        name: Build and run tests
        command: fastlane scan
        environment:
          SCAN_DEVICE: iPhone 8
          SCAN_SCHEME: WebTests
      - store_test_results:
        path: test_output/report.xml
      - store_artifacts:
        path: /tmp/test-results
        destination: scan-test-results
      - store_artifacts:
        path: ~/Library/Logs/scan
        destination: scan-logs

workflows:
  version: 2
  node-android-ios:
    jobs:
      - build:
          filters:
            branches:
              only: master
            tags:
              ignore: /^v.*/
      - ios:
          requires:            
            - build
          filters:
            branches:
              only: master