# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  lane :test do
    gradle(task: "test")
  end
  lane :alpha do |options|
    gradle(task: "clean")

    gradle(task: "assemble")

    sign_apk(
      keystore_path: "${HOME}/keyvault/android.jks",
      alias: "android-fastlane-example",
      storepass: options[:storepass],
      tsa: "http://timestamp.comodoca.com/rfc316",
    )


    zipalign(apk_path: "#{lane_context[SharedValues::SIGNED_APK_PATH]}")
    gradle(task: "test")

  supply(
     track: 'alpha',
     apk: "#{lane_context[SharedValues::SIGNED_APK_PATH]}"
   )
  end
  lane :beta do
    gradle(
      task: "assembleRelease",
      flags: "--no-daemon"
    )
    crashlytics(
      api_token: "170c87df1b26132ef28510f40376dd75cb61f489",
      build_secret: "993c5ab5dbbd48e1f585a02fe66762340c4f8860b2136e177d9a9c6c341de21c",
      groups: "fastlane-tester",
      notes: change_log_since_last_tag
    )
  end
  
  def change_log_since_last_tag
    return changelog_from_git_commits(pretty: '%h %s')
  end
  
  lane :beta2 do
    crashlytics(
      api_token: "170c87df1b26132ef28510f40376dd75cb61f489",
      build_secret: "993c5ab5dbbd48e1f585a02fe66762340c4f8860b2136e177d9a9c6c341de21c",
      groups: "fastlane-tester",
      notes: change_log_since_last_tag
    )
  end
  
  def change_log_since_last_tag
    return changelog_from_git_commits(pretty: '%h %s')
  end
end
